<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameSave.Core\GameSave.Core.csproj" />
    <ProjectReference Include="..\GameSave.Contracts\GameSave.Contracts.csproj" />
  </ItemGroup>
</Project>
