// <auto-generated />
using GameSave.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameSave.Persistence.Migrations;

[DbContext(typeof(GameSaveDbContext))]
[Migration("20260928060000_InitialMetadataDatabase")]
partial class InitialMetadataDatabase
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.12");
#pragma warning restore 612, 618
    }
}
